version: '3.8'
services:
  canton:
    image: ghcr.io/digital-asset/canton-ce:2.10.2
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/dars
      - ./canton:/config
    command: ["--config", "/config/demo.conf"]
